# Site settings
title: 不忘初心
subtitle: 不忘初心，砥砺前行
SEOTitle: 杨光的博客 | YG Blog
header-img: assets/images/base/home-bg.jpg
description: 到不了的地方叫远方，回不去的地方叫故乡，有多少人就这样，一直在路上
keyword: "杨光, Yangguang, YGBlog"
url: https://wangyupei.com
baseurl:

# publish posts or collection documents with a future date
future: true

# SNS settings
RSS: true
github_username: winterdirge
weibo_username: yangguangg
twitter_username: Cofilk
facebook_username: yangguangg
zhihu_username: yangguangg
jianshu_username: 121febe748cc

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "README.zh.md"]
anchorjs: false

# plugin
plugins: [jekyll-paginate]

# markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


#  disqus settings
disqus_username: yangguang

# Google Analytics
ga_track_id: UA-143292095-1
ga_domain: wangyupei.com

# Baidu Analytics
enable_baidu_analytics: true

# Sidebar settings
sidebar: true
sidebar-about-description: 为了美好的明天，我一直在努力
sidebar-avatar:  /assets/images/base/avatar.jpeg

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive web apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page(e.g. post preview)
page-mathjax: false

# Friends
friends: [
  {
    title: 杨光的博客,
    href: "http://wangyupei.com"
  }
]